export const myColors = {
    fontColor:'#404040',
    inActiveColor:"rgba(140,140,140,.6)",
    paleColor:"rgba(140,140,140,.2)"
}


export const lang_library = {
    Afrikaans: 'af',
    Albanian: 'sq',
    Amharic: 'am',
    Arabic: 'ar',
    Armenian: 'hy',
    Azerbaijani: 'az',
    Bashkir: 'ba',
    Basque: 'eu',
    Belarusian: 'be',
    Bengali: 'bn',
    Bosnian: 'bs',
    Bulgarian: 'bg',
    Burmese: 'my',
    Catalan: 'ca',
    Cebuano: 'ceb',
    Chichewa: 'ny',
    Chinese_sim: 'zh-CN', // Chinese (Simplified)
    Chinese_tra: 'zh-TW', // Chinese (Traditional)
    Corsican: 'co',
    Croatian: 'hr',
    Czech: 'cs',
    Danish: 'da',
    Dutch: 'nl',
    English: 'en',
    Esperanto: 'eo',
    Estonian: 'et',
    Finnish: 'fi',
    French: 'fr',
    Frisian: 'fy',
    Galician: 'gl',
    Georgian: 'ka',
    German: 'de',
    Greek: 'el',
    Gujarati: 'gu',
    Haitian_Creole: 'ht',
    Hausa: 'ha',
    Hawaiian: 'haw',
    Hebrew: 'iw',
    Hill_Mari: 'mrj',
    Hindi: 'hi',
    Hmong: 'hmn',
    Hungarian: 'hu',
    Icelandic: 'is',
    Igbo: 'ig',
    Indonesian: 'id',
    Irish: 'ga',
    Italian: 'it',
    Japanese: 'ja',
    Javanese: 'jw',
    Kannada: 'kn',
    Kazakh: 'kk',
    Khmer: 'km',
    Korean: 'ko',
    Kurdish: 'ku',
    Kyrgyz: 'ky',
    Lao: 'lo',
    Latin: 'la',
    Latvian: 'lv',
    Lithuanian: 'lt',
    Luxembourgish: 'lb',
    Macedonian: 'mk',
    Malagasy: 'mg',
    Malay: 'ms',
    Malayalam: 'ml',
    Maltese: 'mt',
    Maori: 'mi',
    Marathi: 'mr',
    Mari: 'mhr',
    Mongolian: 'mn',
    Nepali: 'ne',
    Norwegian: 'no',
    Pashto: 'ps',
    Papiamento: 'pap',
    Persian: 'fa',
    Polish: 'pl',
    Portuguese: 'pt',
    Punjabi: 'pa',
    Romanian: 'ro',
    Russian: 'ru',
    Samoan: 'sm',
    Scots_Gaelic: 'gd',
    Serbian: 'sr',
    Sesotho: 'st',
    Shona: 'sn',
    Sindhi: 'sd',
    Sinhala: 'si',
    Slovak: 'sk',
    Slovenian: 'sl',
    Somali: 'so',
    Spanish: 'es',
    Sundanese: 'su',
    Swahili: 'sw',
    Swedish: 'sv',
    Tagalog_Filipino: 'tl',
    Tajik: 'tg',
    Tamil: 'ta',
    Tatar: 'tt',
    Telugu: 'te',
    Thai: 'th',
    Turkish: 'tr',
    Udmurt: 'udm',
    Ukrainian: 'uk',
    Urdu: 'ur',
    Uzbek: 'uz',
    Vietnamese: 'vi',
    Welsh: 'cy',
    Xhosa: 'xh',
    Yiddish: 'yi',
    Yoruba: 'yo',
    Zulu: 'zu',
  };
  
  
  export const lang_library_formatted = {
    Afrikaans: { apiEntry: 'af', lang: 'Afrikaans', translatedLang: 'Afrikaans' },
    Albanian: { apiEntry: 'sq', lang: 'Albanian', translatedLang: 'Shqip' },
    Amharic: { apiEntry: 'am', lang: 'Amharic', translatedLang: 'አማርኛ' },
    Arabic: { apiEntry: 'ar', lang: 'Arabic', translatedLang: 'العربية' },
    Armenian: { apiEntry: 'hy', lang: 'Armenian', translatedLang: 'Հայերեն' },
    Azerbaijani: { apiEntry: 'az', lang: 'Azerbaijani', translatedLang: 'Azərbaycanca' },
    Bashkir: { apiEntry: 'ba', lang: 'Bashkir', translatedLang: 'Башҡорт' },
    Basque: { apiEntry: 'eu', lang: 'Basque', translatedLang: 'Euskara' },
    Belarusian: { apiEntry: 'be', lang: 'Belarusian', translatedLang: 'Беларуская' },
    Bengali: { apiEntry: 'bn', lang: 'Bengali', translatedLang: 'বাংলা' },
    Bosnian: { apiEntry: 'bs', lang: 'Bosnian', translatedLang: 'Bosanski' },
    Bulgarian: { apiEntry: 'bg', lang: 'Bulgarian', translatedLang: 'Български' },
    Burmese: { apiEntry: 'my', lang: 'Burmese', translatedLang: 'မြန်မာ' },
    Catalan: { apiEntry: 'ca', lang: 'Catalan', translatedLang: 'Català' },
    Cebuano: { apiEntry: 'ceb', lang: 'Cebuano', translatedLang: 'Cebuano' },
    Chichewa: { apiEntry: 'ny', lang: 'Chichewa', translatedLang: 'Chichewa' },
    Chinese: { apiEntry: 'zh-CN', lang: 'Chinese', translatedLang: '中文' },
    Corsican: { apiEntry: 'co', lang: 'Corsican', translatedLang: 'Corsu' },
    Croatian: { apiEntry: 'hr', lang: 'Croatian', translatedLang: 'Hrvatski' },
    Czech: { apiEntry: 'cs', lang: 'Czech', translatedLang: 'Čeština' },
    Danish: { apiEntry: 'da', lang: 'Danish', translatedLang: 'Dansk' },
    Dutch: { apiEntry: 'nl', lang: 'Dutch', translatedLang: 'Nederlands' },
    English: { apiEntry: 'en', lang: 'English', translatedLang: 'English' },
    Esperanto: { apiEntry: 'eo', lang: 'Esperanto', translatedLang: 'Esperanto' },
    Estonian: { apiEntry: 'et', lang: 'Estonian', translatedLang: 'Eesti' },
    Finnish: { apiEntry: 'fi', lang: 'Finnish', translatedLang: 'Suomi' },
    French: { apiEntry: 'fr', lang: 'French', translatedLang: 'Français' },
    Frisian: { apiEntry: 'fy', lang: 'Frisian', translatedLang: 'Frysk' },
    Galician: { apiEntry: 'gl', lang: 'Galician', translatedLang: 'Galego' },
    Georgian: { apiEntry: 'ka', lang: 'Georgian', translatedLang: 'ქართული' },
    German: { apiEntry: 'de', lang: 'German', translatedLang: 'Deutsch' },
    Greek: { apiEntry: 'el', lang: 'Greek', translatedLang: 'Ελληνικά' },
    Gujarati: { apiEntry: 'gu', lang: 'Gujarati', translatedLang: 'ગુજરાતી' },
    Haitian_Creole: { apiEntry: 'ht', lang: 'Haitian Creole', translatedLang: 'Kreyòl Ayisyen' },
    Hausa: { apiEntry: 'ha', lang: 'Hausa', translatedLang: 'Hausa' },
    Hawaiian: { apiEntry: 'haw', lang: 'Hawaiian', translatedLang: 'ʻŌlelo Hawaiʻi' },
    Hebrew: { apiEntry: 'iw', lang: 'Hebrew', translatedLang: 'עברית' },
    Hill_Mari: { apiEntry: 'mrj', lang: 'Hill Mari', translatedLang: 'Кырык мары' },
    Hindi: { apiEntry: 'hi', lang: 'Hindi', translatedLang: 'हिन्दी' },
    Hmong: { apiEntry: 'hmn', lang: 'Hmong', translatedLang: 'Hmoob' },
    Hungarian: { apiEntry: 'hu', lang: 'Hungarian', translatedLang: 'Magyar' },
    Icelandic: { apiEntry: 'is', lang: 'Icelandic', translatedLang: 'Íslenska' },
    Igbo: { apiEntry: 'ig', lang: 'Igbo', translatedLang: 'Igbo' },
    Indonesian: { apiEntry: 'id', lang: 'Indonesian', translatedLang: 'Bahasa Indonesia' },
    Irish: { apiEntry: 'ga', lang: 'Irish', translatedLang: 'Gaeilge' },
    Italian: { apiEntry: 'it', lang: 'Italian', translatedLang: 'Italiano' },
    Japanese: { apiEntry: 'ja', lang: 'Japanese', translatedLang: '日本語' },
    Javanese: { apiEntry: 'jw', lang: 'Javanese', translatedLang: 'Basa Jawa' },
    Kannada: { apiEntry: 'kn', lang: 'Kannada', translatedLang: 'ಕನ್ನಡ' },
    Kazakh: { apiEntry: 'kk', lang: 'Kazakh', translatedLang: 'Қазақ тілі' },
    Khmer: { apiEntry: 'km', lang: 'Khmer', translatedLang: 'ភាសាខ្មែរ' },
    Korean: { apiEntry: 'ko', lang: 'Korean', translatedLang: '한국어' },
    Kurdish: { apiEntry: 'ku', lang: 'Kurdish', translatedLang: 'Kurdî' },
    Kyrgyz: { apiEntry: 'ky', lang: 'Kyrgyz', translatedLang: 'Кыргызча' },
    Lao: { apiEntry: 'lo', lang: 'Lao', translatedLang: 'ພາສາລາວ' },
    Latin: { apiEntry: 'la', lang: 'Latin', translatedLang: 'Latina' },
    Latvian: { apiEntry: 'lv', lang: 'Latvian', translatedLang: 'Latviešu' },
    Lithuanian: { apiEntry: 'lt', lang: 'Lithuanian', translatedLang: 'Lietuvių' },
    Luxembourgish: { apiEntry: 'lb', lang: 'Luxembourgish', translatedLang: 'Lëtzebuergesch' },
    Macedonian: { apiEntry: 'mk', lang: 'Macedonian', translatedLang: 'Македонски' },
    Malagasy: { apiEntry: 'mg', lang: 'Malagasy', translatedLang: 'Malagasy' },
    Malay: { apiEntry: 'ms', lang: 'Malay', translatedLang: 'Bahasa Melayu' },
    Malayalam: { apiEntry: 'ml', lang: 'Malayalam', translatedLang: 'മലയാളം' },
    Maltese: { apiEntry: 'mt', lang: 'Maltese', translatedLang: 'Malti' },
    Maori: { apiEntry: 'mi', lang: 'Maori', translatedLang: 'Māori' },
    Marathi: { apiEntry: 'mr', lang: 'Marathi', translatedLang: 'मराठी' },
    Mari: { apiEntry: 'mhr', lang: 'Mari', translatedLang: 'Марий' },
    Mongolian: { apiEntry: 'mn', lang: 'Mongolian', translatedLang: 'Монгол' },
    Nepali: { apiEntry: 'ne', lang: 'Nepali', translatedLang: 'नेपाली' },
    Norwegian: { apiEntry: 'no', lang: 'Norwegian', translatedLang: 'Norsk' },
    Pashto: { apiEntry: 'ps', lang: 'Pashto', translatedLang: 'پښتو' },
    Papiamento: { apiEntry: 'pap', lang: 'Papiamento', translatedLang: 'Papiamentu' },
    Persian: { apiEntry: 'fa', lang: 'Persian', translatedLang: 'فارسی' },
    Polish: { apiEntry: 'pl', lang: 'Polish', translatedLang: 'Polski' },
    Portuguese: { apiEntry: 'pt', lang: 'Portuguese', translatedLang: 'Português' },
    Punjabi: { apiEntry: 'pa', lang: 'Punjabi', translatedLang: 'ਪੰਜਾਬੀ' },
    Romanian: { apiEntry: 'ro', lang: 'Romanian', translatedLang: 'Română' },
    Russian: { apiEntry: 'ru', lang: 'Russian', translatedLang: 'Русский' },
    Samoan: { apiEntry: 'sm', lang: 'Samoan', translatedLang: 'Gagana Samoa' },
    Scots_Gaelic: { apiEntry: 'gd', lang: 'Scots Gaelic', translatedLang: 'Gàidhlig' },
    Serbian: { apiEntry: 'sr', lang: 'Serbian', translatedLang: 'Српски' },
    Sesotho: { apiEntry: 'st', lang: 'Sesotho', translatedLang: 'Sesotho' },
    Shona: { apiEntry: 'sn', lang: 'Shona', translatedLang: 'Shona' },
    Sindhi: { apiEntry: 'sd', lang: 'Sindhi', translatedLang: 'سنڌي' },
    Sinhala: { apiEntry: 'si', lang: 'Sinhala', translatedLang: 'සිංහල' },
    Slovak: { apiEntry: 'sk', lang: 'Slovak', translatedLang: 'Slovenčina' },
    Slovenian: { apiEntry: 'sl', lang: 'Slovenian', translatedLang: 'Slovenščina' },
    Somali: { apiEntry: 'so', lang: 'Somali', translatedLang: 'Soomaali' },
    Spanish: { apiEntry: 'es', lang: 'Spanish', translatedLang: 'Español' },
    Sundanese: { apiEntry: 'su', lang: 'Sundanese', translatedLang: 'Basa Sunda' },
    Swahili: { apiEntry: 'sw', lang: 'Swahili', translatedLang: 'Kiswahili' },
    Swedish: { apiEntry: 'sv', lang: 'Swedish', translatedLang: 'Svenska' },
    Tagalog_Filipino: { apiEntry: 'tl', lang: 'Tagalog (Filipino)', translatedLang: 'Tagalog' },
    Tajik: { apiEntry: 'tg', lang: 'Tajik', translatedLang: 'Тоҷикӣ' },
    Tamil: { apiEntry: 'ta', lang: 'Tamil', translatedLang: 'தமிழ்' },
    Tatar: { apiEntry: 'tt', lang: 'Tatar', translatedLang: 'Татарча' },
    Telugu: { apiEntry: 'te', lang: 'Telugu', translatedLang: 'తెలుగు' },
    Thai: { apiEntry: 'th', lang: 'Thai', translatedLang: 'ไทย' },
    Turkish: { apiEntry: 'tr', lang: 'Turkish', translatedLang: 'Türkçe' },
    Udmurt: { apiEntry: 'udm', lang: 'Udmurt', translatedLang: 'Удмурт' },
    Ukrainian: { apiEntry: 'uk', lang: 'Ukrainian', translatedLang: 'Українська' },
    Urdu: { apiEntry: 'ur', lang: 'Urdu', translatedLang: 'اردو' },
    Uzbek: { apiEntry: 'uz', lang: 'Uzbek', translatedLang: 'Oʻzbekcha' },
    Vietnamese: { apiEntry: 'vi', lang: 'Vietnamese', translatedLang: 'Tiếng Việt' },
    Welsh: { apiEntry: 'cy', lang: 'Welsh', translatedLang: 'Cymraeg' },
    Xhosa: { apiEntry: 'xh', lang: 'Xhosa', translatedLang: 'isiXhosa' },
    Yiddish: { apiEntry: 'yi', lang: 'Yiddish', translatedLang: 'ייִדיש' },
    Yoruba: { apiEntry: 'yo', lang: 'Yoruba', translatedLang: 'Yorùbá' },
    Zulu: { apiEntry: 'zu', lang: 'Zulu', translatedLang: 'isiZulu' },
  };
  

 