export const myColors = {
    fontColor:'#404040',
    inActiveColor:"rgba(140,140,140,.6)",
    paleColor:"rgba(140,140,140,.2)"
}


export const lang_library = {
    Afrikaans: 'af',
    Albanian: 'sq',
    Amharic: 'am',
    Arabic: 'ar',
    Armenian: 'hy',
    Azerbaijani: 'az',
    Bashkir: 'ba',
    Basque: 'eu',
    Belarusian: 'be',
    Bengali: 'bn',
    Bosnian: 'bs',
    Bulgarian: 'bg',
    Burmese: 'my',
    Catalan: 'ca',
    Cebuano: 'ceb',
    Chichewa: 'ny',
    Chinese_sim: 'zh-CN', // Chinese (Simplified)
    Chinese_tra: 'zh-TW', // Chinese (Traditional)
    Corsican: 'co',
    Croatian: 'hr',
    Czech: 'cs',
    Danish: 'da',
    Dutch: 'nl',
    English: 'en',
    Esperanto: 'eo',
    Estonian: 'et',
    Finnish: 'fi',
    French: 'fr',
    Frisian: 'fy',
    Galician: 'gl',
    Georgian: 'ka',
    German: 'de',
    Greek: 'el',
    Gujarati: 'gu',
    Haitian_Creole: 'ht',
    Hausa: 'ha',
    Hawaiian: 'haw',
    Hebrew: 'iw',
    Hill_Mari: 'mrj',
    Hindi: 'hi',
    Hmong: 'hmn',
    Hungarian: 'hu',
    Icelandic: 'is',
    Igbo: 'ig',
    Indonesian: 'id',
    Irish: 'ga',
    Italian: 'it',
    Japanese: 'ja',
    Javanese: 'jw',
    Kannada: 'kn',
    Kazakh: 'kk',
    Khmer: 'km',
    Korean: 'ko',
    Kurdish: 'ku',
    Kyrgyz: 'ky',
    Lao: 'lo',
    Latin: 'la',
    Latvian: 'lv',
    Lithuanian: 'lt',
    Luxembourgish: 'lb',
    Macedonian: 'mk',
    Malagasy: 'mg',
    Malay: 'ms',
    Malayalam: 'ml',
    Maltese: 'mt',
    Maori: 'mi',
    Marathi: 'mr',
    Mari: 'mhr',
    Mongolian: 'mn',
    Nepali: 'ne',
    Norwegian: 'no',
    Pashto: 'ps',
    Papiamento: 'pap',
    Persian: 'fa',
    Polish: 'pl',
    Portuguese: 'pt',
    Punjabi: 'pa',
    Romanian: 'ro',
    Russian: 'ru',
    Samoan: 'sm',
    Scots_Gaelic: 'gd',
    Serbian: 'sr',
    Sesotho: 'st',
    Shona: 'sn',
    Sindhi: 'sd',
    Sinhala: 'si',
    Slovak: 'sk',
    Slovenian: 'sl',
    Somali: 'so',
    Spanish: 'es',
    Sundanese: 'su',
    Swahili: 'sw',
    Swedish: 'sv',
    Tagalog_Filipino: 'tl',
    Tajik: 'tg',
    Tamil: 'ta',
    Tatar: 'tt',
    Telugu: 'te',
    Thai: 'th',
    Turkish: 'tr',
    Udmurt: 'udm',
    Ukrainian: 'uk',
    Urdu: 'ur',
    Uzbek: 'uz',
    Vietnamese: 'vi',
    Welsh: 'cy',
    Xhosa: 'xh',
    Yiddish: 'yi',
    Yoruba: 'yo',
    Zulu: 'zu',
  };
  
  